# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fe7315464c7ec4014fa17fa793926bdf"
application_url = "https://teen-pipes-jessica-cognitive.trycloudflare.com"
embedded = true
name = "review-app"
handle = "review-app-172"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products, write_products"

[auth]
redirect_urls = [
  "https://teen-pipes-jessica-cognitive.trycloudflare.com/auth/callback",
  "https://teen-pipes-jessica-cognitive.trycloudflare.com/auth/shopify/callback",
  "https://teen-pipes-jessica-cognitive.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
